# This file created by conda-build 25.4.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed May  7 16:06:12 2025
# ------------------------------------------------

package:
  name: libxml2
  version: 2.13.8
source:
  patches:
    - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
  sha256: df8d4148cc3473d18e07b72f501aac0dcb7c055c8f537da21c0a985be948fc16
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.13.8/libxml2-v2.13.8.tar.gz
build:
  number: '0'
  run_exports:
    - libxml2 >=2.13.8,<2.14.0a0
  string: h52572c6_0
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - automake 1.17 pl5321h694c41f_0
    - clang_bootstrap_osx-arm64 18.1.8 hf1725c4_24
    - libiconv 1.18 h4b5e92a_1
    - libltdl 2.4.3a h240833e_0
    - libtool 2.5.4 h240833e_0
    - m4 1.4.18 haf1e3a3_1001
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - perl 5.32.1 7_h10d778d_perl5
    - pkg-config 0.29.2 hf7e621a_1009
  host:
    - icu 75.1 hfee45f7_0
    - libiconv 1.18 hfe07756_1
    - liblzma 5.8.1 h39f12f2_1
    - liblzma-devel 5.8.1 h39f12f2_1
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - icu >=75.1,<76.0a0
    - libiconv >=1.18,<2.0a0
    - liblzma >=5.8.1,<6.0a0
    - libzlib >=1.3.1,<2.0a0
  run_constrained: []
test:
  commands:
    - echo on
    - xmllint test.xml
    - mkdir -p "${PREFIX}/etc/xml"
    - cp   test_catalog.xml "${PREFIX}/etc/xml/catalog"
    - xmlcatalog "" "http://www.w3.org/2001/xml.xsd" | grep -x -F -e "file://test-uri-override"
    - rm  "${PREFIX}/etc/xml/catalog"
    - xmlcatalog "" "test-id" | grep -x -F -e "No entry for URI test-id"
    - xmlcatalog "test_catalog.xml" "test-id" | grep -x -F -e "file://test-uri"
    - export XML_CATALOG_FILES="file://$(pwd)/test_catalog.xml"
    - xmlcatalog "" "test-id" | grep -x -F -e "file://test-uri"
    - xmlcatalog "" "http://www.w3.org/2009/01/xml.xsd" | grep -x -F -e "No entry
      for URI http://www.w3.org/2009/01/xml.xsd"
  files:
    - test.xml
    - test_catalog.xml
  requires:
    - ripgrep
about:
  description: 'Though libxml2 is written in C a variety of language

    bindings make it available in other environments.

    '
  dev_url: https://git.gnome.org/browse/libxml2/
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/devhelp/index.html
  doc_url: http://xmlsoft.org/html/index.html
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250507.2.1
  recipe-maintainers:
    - gillins
    - isuruf
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
    - scopatz
  remote_url: https://github.com/conda-forge/libxml2-feedstock
  sha: 1940c447f8162ddb8316cda0343165f881ac601f
