context:
  name: "cpp-expected"
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/TartanLlama/expected/archive/v${{ version }}.tar.gz
  sha256: 1db357f46dd2b24447156aaf970c4c40a793ef12a8a9c2ad9e096d9801368df6

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

tests:
  - package_contents:
      include:
        - tl/expected.hpp
      files:
        - "**/share/cmake/tl-expected/tl-expected-config.cmake"
        - "**/share/cmake/tl-expected/tl-expected-config-version.cmake"

about:
  homepage: https://github.com/TartanLlama/expected
  license: CC0-1.0
  license_file: LICENSE
  summary: C++11/14/17 std::expected with functional-style extensions
  description: C++11/14/17 std::expected with functional-style extensions
  documentation: https://github.com/TartanLlama/expected#readme
  repository: https://github.com/TartanLlama/expected

extra:
  recipe-maintainers:
    - JohanMabille
    - wolfv
